services:
  web-app:
    container_name: web-app
    ports:
      - "5000"
    command: "python run.py"
  postgres:
    - container_name: pgdb
    - image: docker.io/library/postgres:latest
    env:
    - name: POSTGRES_PASSWORD
      value: password
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgsql-pvc
  volumes:
  - name: pgsql-pvc
    persistentVolumeClaim:
      claimName: pgsql-pvc
