#apiVersion: v1
#kind: Pod
#metadata:
#  name: web-app
#  annotations:
#    io.podman.annotations.map-gw: "true"
#    io.podman.annotations.map-host-loopback: "true"
#spec:
#  hostNetwork: true
#  containers:
#  - name: web-app
#    image: localhost/web-app:latest
#    command: ["python", "run.py"]
#    ports:
#    - containerPort: 5000
---
# PostgreSQL DB
apiVersion: v1
kind: Pod
metadata:
  name: postgresql
spec:
  hostNetwork: true
  containers:
  - name: postgres
    image: docker.io/library/postgres:latest
    env:
    - name: POSTGRES_PASSWORD
      value: password
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgsql-pvc
  volumes:
  - name: pgsql-pvc
    persistentVolumeClaim:
      claimName: pgsql-pvc
