INSERT INTO album (id, name, artistowner) VALUES
    (0, 'Sliding', 0),
    (1, 'Here, Look', 0),
    (2, 'Deslocado', 1),
    (3, 'All the Lost Souls', 2),
    (4, 'Just Cosmo', 3),
    (5, 'Imaginal Disk', 4),
    (6, 'Delusions Of Grandeur', 5),
    (7, 'Submarine - Original Songs From The Film By Alex Turner', 6),
    (8, 'B-Side Vol.3 (2011-2015)', 7),
    (9, 'Duplicator A', 8),
    (10, 'Duplicator B', 9),
    (11, 'Happy Album', 10),
    (12, 'Space Jam', 11),
    (13, '色々', 12),
    (14, 'Kaiju', 13);