insert into public.artist (id, name)
values  (0, 'Habe'),
        (1, 'NAPA'),
        (2, 'James Blunt'),
        (3, 'Cosmo Pyke'),
        (4, 'Magdalena Bay'),
        (5, 'HOL!DAY'),
        (6, 'Alex Turner'),
        (7, 'Rav'),
        (8, 'Duplicator'),
        (9, 'Duplicator'),
        (10, '😀😃'),
        (11, '👽👾'),
        (12, '須田景凪'),
        (13, 'Sakanaction');